---
version: '3.8'

services:
  freeswitch:
    image: jigate/freeswitch:latest
    restart: ${RESTART_POLICY:-unless-stopped}
    ports:
      - '${FREESWITCH_EXTERNAL_SIP_PORT:-5060}:${FREESWITCH_EXTERNAL_SIP_PORT:-5060}/udp'
      - '${FREESWITCH_RTP_START_PORT:-20200}-${FREESWITCH_RTP_END_PORT:-20250}:${FREESWITCH_RTP_START_PORT:-20200}-${FREESWITCH_RTP_END_PORT:-20250}/udp'
    volumes:
      - ../jigate/freeswitch/etc/freeswitch:/etc/freeswitch
      - ../jigate/freeswitch/usr/share/freeswitch/sounds:/usr/share/freeswitch/sounds
    environment:
      - JIGASI_SIP_PASSWORD
      - FREESWITCH_ESL_PASSWORD
      - FREESWITCH_EXTERNAL_IP=${FREESWITCH_EXTERNAL_IP:-127.0.0.1}
      - FREESWITCH_EXTERNAL_SIP_PORT=${FREESWITCH_EXTERNAL_SIP_PORT:-5060}
      - FREESWITCH_INTERNAL_IP=${FREESWITCH_INTERNAL_IP:-interface:ipv4/eth1}
      - FREESWITCH_INTERNAL_SIP_PORT=${JIGASI_SIP_PORT:-5060}
      - FREESWITCH_REGISTRATION_PASSWORD
      - FREESWITCH_REGISTRATION_USERNAME=${FREESWITCH_REGISTRATION_USER:-user}
      - FREESWITCH_RTP_END_PORT=${FREESWITCH_RTP_END_PORT:-20250}
      - FREESWITCH_RTP_START_PORT=${FREESWITCH_RTP_START_PORT:-20200}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - SIPGW_SIP_DOMAIN=${SIPGW_SIP_DOMAIN:-meet.jitsi}
      - SIPGW_SIP_PASSWORD
      - SIPGW_SIP_PORT=${SIPGW_SIP_PORT:-5060}
      - SIPGW_SIP_SERVER=${SIPGW_SIP_SERVER:-sipgw.meet.jitsi}
      - SIPGW_SIP_USERNAME=${SIPGW_SIP_USERNAME:-jigate}
    networks:
      freeswitch:
        aliases:
          - ${JIGASI_SIP_SERVER:-freeswitch.meet.jitsi}
      meet.jitsi:
        aliases:
          - ${JIGASI_SIP_SERVER:-freeswitch.meet.jitsi}

  jigate:
    image: jigate/jigate:latest
    restart: ${RESTART_POLICY:-unless-stopped}
    volumes:
      - ../jigate:/home/node/jigate
    environment:
      - JIGASI_SIP_URI=jigasi@meet.jitsi
      - FREESWITCH_ESL_PASSWORD
      - FREESWITCH_IVR_DESTINATION=${FREESWITCH_IVR_DESTINATION:-1000}
      - FREESWITCH_SERVER=${JIGASI_SIP_SERVER:-freeswitch.meet.jitsi}
      - LOG_LEVEL
    networks:
      meet.jitsi:
    depends_on:
      - freeswitch

  jigasi:
    environment:
      - JIGASI_SIP_SERVER=${JIGASI_SIP_SERVER:-freeswitch.meet.jitsi}
      - JIGASI_SIP_PORT=${JIGASI_SIP_PORT:-5060}
      - JIGASI_SIP_URI=jigasi@meet.jitsi
    depends_on:
      - freeswitch

  jicofo:
    environment:
      - JIGASI_SIP_URI=jigasi@meet.jitsi

networks:
  freeswitch:
