---
version: '3.8'

services:
  sipgw:
    image: jigate/sipgw:latest
    ports:
      - '${SIPGW_EXTERNAL_SIP_PORT:-5060}:5060/udp'
      - '${SIPGW_RTP_START_PORT:-20200}-${SIPGW_RTP_END_PORT:-20250}:${SIPGW_RTP_START_PORT:-20200}-${SIPGW_RTP_END_PORT:-20250}/udp'
    environment:
      - JIGATE_SIP_PASSWORD
      - JIGATE_SIP_PORT=${JIGATE_SIP_PORT:-5060}
      - JIGATE_SIP_USERNAME=${JIGATE_SIP_USERNAME:-jigate}
      - JIGATE_SIP_DOMAIN=${JIGATE_SIP_DOMAIN:-meet.jitsi}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - SIPGW_EXTERNAL_IP=${SIPGW_EXTERNAL_IP:-127.0.0.1}
      - SIPGW_RTP_END_PORT=${SIPGW_RTP_END_PORT:-20250}
      - SIPGW_RTP_START_PORT=${SIPGW_RTP_START_PORT:-20200}
      - SIPGW_USER_PASSWORD
    networks:
      sipgw:
        aliases:
          - ${JIGATE_SIP_SERVER:-sipgw.meet.jitsi}
      jigate:
        aliases:
          - ${JIGATE_SIP_SERVER:-sipgw.meet.jitsi}

  jigate:
    depends_on:
      - sipgw

networks:
  sipgw:
