export enum AudioMessage {
    ConferenceEndedByHost = 'en/us/conference_ended_by_host.wav',
    ConferenceStarted = 'en/us/conference_started.wav',
    EnterYourMeetingId = 'en/us/enter_your_meeting_id.wav',
    HandIsLowered = 'en/us/hand_is_lowered.wav',
    HandIsRaised = 'en/us/hand_is_raised.wav',
    NotAllowedToUnmute = 'en/us/not_allowed_to_unmute.wav',
    PleaseUnmute = 'en/us/please_unmute.wav',
    PleaseWaitConferenceStartShortly = 'en/us/please_wait_conference_start_shortly.wav',
    PleaseWaitToJoinConference = 'en/us/please_wait_to_join_conference.wav',
    SomethingWentWrong = 'en/us/something_went_wrong.wav',
    UnknownMeetingId = 'en/us/unknown_meeting_id.wav',
    WeDidNotReceiveAnyInput = 'en/us/we_did_not_receive_any_input.wav',
    YouAreInTheConference = 'en/us/you_are_in_the_conference.wav',
    YouAreMuted = 'en/us/you_are_muted.wav',
    YouAreUnmuted = 'en/us/you_are_unmuted.wav',
}
